; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = firmware/src
include_dir = firmware/include
lib_dir = firmware/lib
data_dir = firmware/data
test_dir = firmware/test

;[env:seeed_xiao_rp2040]
[env:waveshare_rp2040_zero]
;platform = https://github.com/Seeed-Studio/platform-seeedboards.git
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
;board = seeed-xiao-rp2040
board = waveshare_rp2040_zero
framework = arduino

monitor_speed = 115200
monitor_filters = default, time, colorize  ; 額外加上時間戳和顏色，更好閱讀

board_build.core = earlephilhower
board_build.arduino.earlephilhower.usb_vid = 0x256F
board_build.arduino.earlephilhower.usb_pid = 0xC631
board_build.arduino.earlephilhower.usb_manufacturer = 3Dcn
board_build.arduino.earlephilhower.usb_product = CAD Mouse MK2
build_flags = 
	-DUSE_TINYUSB
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
lib_deps = 
	infineon/XENSIV 3D Magnetic Sensor TLx493D@1.1.0
	bxparks/AceButton@^1.10.1
	adafruit/Adafruit NeoPixel@1.12.3



